// Caeleigh's Florida Keys Field Guide — species database
// category tab colors are set in styles.css via [data-cat="..."]
const SPECIES = [

/* ============ SHARKS ============ */
{id:"nurse-shark", cat:"sharks", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Nurse_shark_top_view.jpg", name:"Nurse Shark", size:"9–14 ft", spotted:true,
  desc:"A slow, bottom-hugging shark with a wide flat head and two barbels (whiskers) under its chin for sniffing out food. It's nocturnal, resting in caves and under ledges by day and hunting at night.",
  role:"Nurse sharks vacuum up crab, shrimp, lobster, and slow fish from the seafloor, which keeps those populations in balance. Because they rest in the same reef ledges for years, they're a sign a reef has healthy hiding structure."},
{id:"caribbean-reef-shark", cat:"sharks", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Caribbean_reef_shark.JPG", name:"Caribbean Reef Shark", size:"3–8 ft", spotted:true,
  desc:"The shark you're most likely to see on a Keys reef dive — dark grey above, white belly, and docile around people. It can pump water over its gills while lying still on the sand, unlike most sharks.",
  role:"As the top mid-level predator on the reef, it culls sick and slow reef fish and octopus, which keeps prey species from overgrazing the coral and sponges around them."},
{id:"silky-shark", cat:"sharks", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Silky_sharks_swimming_in_groups.png", name:"Silky Shark", size:"up to 10 ft",
  desc:"Named for its smooth, silky-feeling skin, this slender shark patrols open water well offshore of the reef, often near drop-offs and current lines.",
  role:"It preys on schooling fish like tuna and mackerel offshore, helping keep those bait schools from exploding in number before they ever reach the reef."},
{id:"great-white-shark", cat:"sharks", img:"https://commons.wikimedia.org/wiki/Special:FilePath/White_shark.jpg", name:"Great White Shark", size:"13–16 ft",
  desc:"The largest predatory shark, built for powerful bursts of speed. Great whites are rare visitors to Florida waters, usually tracked passing through in cooler months.",
  role:"As an apex predator of the wider Atlantic, it keeps seal and large fish populations in check far offshore, which indirectly keeps the whole ocean food web from tipping out of balance."},
{id:"mako-shark", cat:"sharks", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Kurzflossen-Mako.jpg", name:"Shortfin Mako Shark", size:"6–13 ft",
  desc:"The fastest shark in the ocean, able to burst to speeds over 40 mph to chase down fast prey like tuna and swordfish.",
  role:"Its speed lets it thin out fast, strong fish that other predators can't catch, keeping offshore fish populations from becoming dominated by only the fastest breeders."},
{id:"oceanic-whitetip-shark", cat:"sharks", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Oceanic_whitetip_shark_at_Elphinstone_Reef.jpg", name:"Oceanic Whitetip Shark", size:"6–10 ft",
  desc:"Easy to identify by its long, rounded, white-tipped fins. It roams the open ocean far from shore and rarely encounters divers.",
  role:"It's an opportunistic scavenger and hunter far offshore, cleaning up injured or dead fish and squid, which keeps the open ocean from accumulating carrion."},
{id:"tiger-shark", cat:"sharks", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Tiger_shark.jpg", name:"Tiger Shark", size:"10–14 ft",
  desc:"Named for the dark vertical stripes on juveniles, tiger sharks eat almost anything, from sea turtles to license plates, earning them the nickname 'garbage cans of the sea.'",
  role:"By eating sick and injured sea turtles and rays, tiger sharks keep seagrass-grazing populations healthy and prevent overgrazing of the Keys' seagrass meadows."},
{id:"bonnethead-shark", cat:"sharks", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Bonnethead_shark.jpg", name:"Bonnethead Shark", size:"2–4 ft",
  desc:"The smallest member of the hammerhead family, with a shovel-shaped head instead of a wide hammer. It's one of the only sharks known to eat seagrass along with its normal diet of crabs.",
  role:"It patrols shallow seagrass flats for crabs and shrimp, and its odd partial diet of seagrass may even help cycle nutrients through the meadow."},
{id:"scalloped-hammerhead", cat:"sharks", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Scalloped_hammerhead_cocos.jpg", name:"Scalloped Hammerhead", size:"6–9 ft",
  desc:"Its hammer-shaped head (called a cephalofoil) has a scalloped, wavy front edge and is packed with sensors that detect the tiny electric fields of hidden prey.",
  role:"It hunts stingrays buried in the sand, and by keeping ray numbers in check it protects shellfish beds that rays would otherwise overwhelm."},
{id:"smooth-hammerhead", cat:"sharks", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Hammerhead_Shark_-_Marko_Dimitrijevic.jpg", name:"Smooth Hammerhead", size:"11–13 ft",
  desc:"Similar to the scalloped hammerhead but with a smooth, unscalloped front edge on its head, and it tolerates cooler water better than its relatives.",
  role:"It hunts rays, squid, and schooling fish in open water, spreading predation pressure across a wider range of prey than reef-bound sharks."},
{id:"great-hammerhead", cat:"sharks", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Hammerhead_shark%2C_Cocos_Island%2C_Costa_Rica.jpg", name:"Great Hammerhead Shark", size:"11–20 ft",
  desc:"The largest hammerhead species, with a nearly straight-edged head. It's a specialist ray hunter, using its head to pin stingrays to the seafloor.",
  role:"As one of the reef's top predators, it controls ray and large fish populations, which keeps grazing pressure on seagrass and shellfish beds in check."},
{id:"bull-shark", cat:"sharks", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Bullshark.JPG", name:"Bull Shark", size:"7–11 ft",
  desc:"A stocky, aggressive shark that can tolerate fresh water and is regularly found far up rivers, not just in the ocean.",
  role:"Because it moves between reefs, mangroves, and rivers, the bull shark links nutrients and predation pressure across very different Keys habitats."},
{id:"blacktip-shark", cat:"sharks", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Carcharhinus_melanopterus2.jpg", name:"Blacktip Shark", size:"4–6 ft",
  desc:"A fast, energetic shark known for spinning out of the water while feeding on schools of baitfish, a behavior called a 'spinner leap.'",
  role:"It keeps schooling baitfish like sardines from overpopulating nearshore waters, which keeps the smaller fish moving and the food web balanced."},
{id:"lemon-shark", cat:"sharks", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Lemonshark(2).jpg", name:"Lemon Shark", size:"8–10 ft",
  desc:"Named for its pale yellow-brown skin, which helps it blend into sandy flats. Juveniles use mangrove-lined shallows as nursery grounds.",
  role:"Young lemon sharks growing up in Keys mangrove nurseries later become reef predators, making healthy mangroves essential to the shark population offshore."},
{id:"sand-tiger-shark", cat:"sharks", img:"https://commons.wikimedia.org/wiki/Special:FilePath/MNMS_Sand_Tiger_Shark_USS_Tarpon_(48783007938).jpg", name:"Sand Tiger Shark", size:"6–10 ft",
  desc:"Despite a mouthful of ragged, snaggle teeth that make it look fierce, the sand tiger is generally slow and docile, and it can gulp air at the surface to hover motionless underwater.",
  role:"It hunts along sandy bottoms and wrecks for fish and squid, helping control mid-sized fish populations in these lower-traffic habitats."},

/* ============ FISH & RAYS ============ */
{id:"mangrove-snapper", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Mangrove_snapper%2C_Lutjanus_griseus.jpg", name:"Mangrove Snapper", size:"1–2 ft", spotted:true,
  desc:"A grey-red snapper that starts life hiding among mangrove roots before moving out to deeper reefs as an adult.",
  role:"As juveniles, they shelter in mangrove roots and eat small invertebrates; as adults on the reef, they help control smaller fish and crustacean numbers."},
{id:"scrawled-filefish", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Scrawled_filefish_at_Abu_Galawa_Kebir.JPG", name:"Scrawled Filefish", size:"1–3 ft",
  desc:"Covered in blue squiggles and dark spots, it can change color to match its surroundings and has a thin, file-like spine on its back.",
  role:"It's one of the few fish that regularly eats fire coral and other stinging invertebrates most fish avoid, helping keep those species from overrunning a reef."},
{id:"white-spotted-filefish", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Whitespotted_filefish_Cantherhines_macrocerus_(4675040909).jpg", name:"White-spotted Filefish", size:"6–10 in",
  desc:"A slow, deliberate swimmer that can shift color from white to brown to match a gorgonian or sponge it's hiding against.",
  role:"It grazes on soft corals, sponges, and algae, helping keep those fast-growing organisms from crowding out slower-growing hard corals."},
{id:"queen-triggerfish", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Balistes_vetula_(queen_triggerfish)_(San_Salvador_Island%2C_Bahamas)_1_(16149228661).jpg", name:"Queen Triggerfish", size:"1–2 ft",
  desc:"Brightly colored with blue lines across its face, it can lock its dorsal spine upright to wedge itself into reef crevices when threatened.",
  role:"It's one of the few reef fish that can crack open sea urchins and other spiny invertebrates, keeping urchin numbers from exploding and overgrazing coral."},
{id:"smooth-trunkfish", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Lactophrys_triqueter.jpg", name:"Smooth (Boxy) Trunkfish", size:"1 ft",
  desc:"Its body is fused into a rigid bony box, so it swims by fluttering its fins rather than bending its body, giving it a slow, hovering motion.",
  role:"It picks small invertebrates out of sand and rubble, helping recycle nutrients on the sea floor around the reef."},
{id:"spotted-trunkfish", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Lactophrys_bicaudalis.jpg", name:"Spotted Trunkfish", size:"1–1.5 ft",
  desc:"Covered in dark polka dots, this armored, box-shaped fish can secrete a mild toxin from its skin when stressed.",
  role:"Like other trunkfish, it grazes small invertebrates from sand and rubble patches, helping keep those populations in check near the reef base."},
{id:"brown-chromis", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Brown_chromis_Chromis_multilineata_(4676202482).jpg", name:"Brown Chromis", size:"3–5 in",
  desc:"A small schooling damselfish that hovers in loose clouds just above the reef, snapping up plankton drifting by in the current.",
  role:"Huge schools of chromis are a major link between open-water plankton and the reef food web, feeding larger predatory fish."},
{id:"blue-chromis", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Chromis_cyanea_(blue_chromis)_(San_Salvador_Island%2C_Bahamas)_3_(16151575955).jpg", name:"Blue Chromis", size:"2–3 in",
  desc:"A small, vividly blue damselfish that schools in large numbers over coral heads, picking plankton from the water column.",
  role:"Like brown chromis, it funnels energy from planktonic food into the reef system, sustaining the fish that prey on it."},
{id:"blue-tang", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Acanthurus_coeruleus_(blue_tang)_(San_Salvador_Island%2C_Bahamas)_1_(15962485708).jpg", name:"Blue Tang", size:"1 ft",
  desc:"A vivid blue surgeonfish with a sharp, scalpel-like spine at the base of its tail used for defense.",
  role:"It grazes algae off coral and rock, which is critical — without algae grazers like the blue tang, algae can smother and kill coral."},
{id:"scrawled-cowfish", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Juvie_Acanthostracion_quadricornis.jpg", name:"Scrawled Cowfish", size:"1–1.5 ft", spotted:true,
  desc:"A boxy, horned fish covered in blue squiggles, with two small horn-like spines above its eyes, giving it its 'cow' name.",
  role:"It feeds on sponges, algae, and small invertebrates in sand and rubble, helping keep those populations from overgrowing reef structure."},
{id:"dog-snapper", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Gfp-dog-snapper.jpg", name:"Dog Snapper", size:"1–2.5 ft",
  desc:"A large snapper named for its prominent canine-like teeth, usually found solo or in small groups near reef structure.",
  role:"As a mid-level predator it controls populations of smaller reef fish and crustaceans, helping balance the reef food web."},
{id:"schoolmaster", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Lutjanus_apodus%2C_Adult_(Schoolmaster_Snapper)_(2848471669).jpg", name:"Schoolmaster Snapper", size:"1–1.5 ft",
  desc:"A yellow-finned snapper that, true to its name, forms tight schools around reef structure and mangrove edges during the day.",
  role:"It links mangrove nursery habitat to the reef, since juveniles grow up in mangroves before schooling on reefs as adults."},
{id:"gray-snapper", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Grey_snapper_-_Lutjanus_griseus.jpg", name:"Gray (Mangrove) Snapper", size:"1–2 ft",
  desc:"A wary, adaptable snapper found from mangrove creeks to deep reefs, able to quickly change shade to match its surroundings.",
  role:"It's an important predator of small fish and shrimp throughout the Keys, and its use of both mangroves and reefs ties those ecosystems together."},
{id:"yellowtail-snapper", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/2006-10-06_18_-_Yellowtail_Snapper.JPG", name:"Yellowtail Snapper", size:"1–1.5 ft",
  desc:"Easily spotted by the bright yellow stripe running from nose to tail, it often swims in loose schools well above the reef.",
  role:"It feeds on plankton and small invertebrates in open water over the reef, forming a food link between the water column and the reef floor."},
{id:"sergeant-major", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Abudefduf_saxatilis.jpg", name:"Sergeant Major", size:"6–9 in",
  desc:"A common damselfish with five bold black bars on a yellow-and-silver body, named for its stripes resembling military rank insignia.",
  role:"It aggressively guards patches of algae it farms on the reef, and defends its purple egg clusters, shaping small-scale algae growth on the reef."},
{id:"spotfin-butterflyfish", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Chaetodon_ocellatus_-_spotfin_butterflyfish_-_Bay_of_Pigs_-_Cuba.jpg", name:"Spotfin Butterflyfish", size:"6–8 in",
  desc:"A silvery, black-and-white banded fish with a false eyespot near its tail to confuse predators about which end is which.",
  role:"It picks small invertebrates like worms and crustaceans from coral crevices, helping keep those populations from overrunning coral heads."},
{id:"foureye-butterflyfish", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Chaetodon_capistratus2.jpg", name:"Foureye Butterflyfish", size:"5–6 in",
  desc:"Named for the large black spot near its tail that mimics a second pair of eyes, tricking predators into misjudging which direction it will flee.",
  role:"It feeds on coral polyps and small invertebrates, and because it usually pairs for life, it's used by scientists as an indicator of long-term reef health."},
{id:"banded-butterflyfish", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Chaetodon_striatus_-_banded_butterflyfish_-_Bay_of_Pigs_-_Cuba.jpg", name:"Banded Butterflyfish", size:"5–6 in",
  desc:"Marked with a wide black band through the eye and another near the tail, it often forms small groups over reef structure.",
  role:"It picks at coral polyps, worms, and small crustaceans, helping keep those invertebrate populations balanced on the reef."},
{id:"blue-striped-grunt", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Haemulon_sciurus.jpg", name:"Bluestriped Grunt", size:"6–12 in",
  desc:"Named for the grunting sound it makes by grinding its teeth (amplified by its swim bladder), it schools by day and forages at night.",
  role:"By day, huge schools shelter over reef structure, and at night they migrate to seagrass beds to feed, physically ferrying nutrients between the two habitats."},
{id:"white-grunt", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Haemulon_plumieri_(white_grunt)_(San_Salvador_Island%2C_Bahamas)_5_(16182172972).jpg", name:"White Grunt", size:"10–14 in",
  desc:"A silvery-grey grunt with yellow-striped cheeks, one of the most common reef fish in the Keys, often seen in large daytime schools.",
  role:"Like other grunts, it moves nutrients from nighttime feeding grounds in seagrass back to the reef where it rests, fertilizing coral with its waste."},
{id:"small-mouth-grunt", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Haemulon_chrysargyreum.JPG", name:"Smallmouth Grunt", size:"7–9 in",
  desc:"A slender grunt with a noticeably small mouth adapted for picking tiny invertebrates rather than larger prey.",
  role:"It feeds mainly on tiny crustaceans in the sand at night, helping control those populations near the reef base."},
{id:"spanish-grunt", cat:"fish", name:"Spanish Grunt", size:"10–12 in",
  desc:"A deep-bodied grunt with bold yellow stripes, usually found in small groups hovering close to reef ledges.",
  role:"Like other grunts, it recycles nutrients between nighttime foraging grounds and daytime reef shelter, supporting coral growth with its waste."},
{id:"porkfish", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Porkfish_Anisotremus_virginicus.jpg", name:"Porkfish", size:"8–12 in",
  desc:"A striking yellow-and-silver fish with two black bars through its eyes, closely related to grunts.",
  role:"Juveniles act as cleaner fish, picking parasites off other reef fish, while adults forage at night for invertebrates, linking cleaning stations to nutrient cycling."},
{id:"honey-damselfish", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Threespot_Damselfish_JG.jpg", name:"Honey (Threespot) Damselfish", size:"2–3 in",
  desc:"A small, feisty damselfish that turns yellow-orange as a juvenile and fiercely defends its patch of algae from intruders many times its size.",
  role:"It actively 'farms' and defends specific algae patches, which changes the composition of algae on the reef in the areas it guards."},
{id:"yellowtail-damselfish", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Yellowtail_damselfish_Microspathodon_chrysurus_(4657125482).jpg", name:"Yellowtail Damselfish", size:"2–3 in",
  desc:"A deep blue damselfish speckled with iridescent blue dots as a juvenile, fading as it matures.",
  role:"Like other damselfish, it grazes and defends algae patches on the reef, influencing which algae species dominate small territories."},
{id:"cottonwick", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Haemulon_melanurum.jpg", name:"Cottonwick", size:"8–11 in",
  desc:"A grunt with a distinctive dark saddle patch near its tail, often mixing into schools with other grunt species over the reef by day.",
  role:"It joins the nightly migration of grunts from reef to seagrass to feed, contributing to the nutrient transfer between those habitats."},
{id:"highhat", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Pareques_acuminatus.jpg", name:"Highhat", size:"6–10 in",
  desc:"A shy, striped drum fish that hides in reef crevices and wrecks by day, marked with bold black-and-white horizontal stripes.",
  role:"It feeds on small worms and crustaceans hidden in sand and rubble at night, helping control those populations near reef structure."},
{id:"lionfish", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Common_lion_fish_Pterois_volitans.jpg", name:"Lionfish (Invasive)", size:"1–1.5 ft",
  desc:"A striped, venomous-spined fish native to the Indo-Pacific that has invaded Florida and Caribbean reefs, where it has no natural predators.",
  role:"Lionfish eat huge numbers of small native reef fish and shrimp with no local predator to control them, so removing lionfish is one of the most important things divers in the Keys can do for reef health."},
{id:"jackknife-fish", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Equetus_lanceolatus_in_Madagascar_Reef.jpg", name:"Jackknife Fish", size:"6–9 in",
  desc:"A striking black-and-white striped drum with a long, sail-like dorsal fin, usually seen alone hovering near reef ledges.",
  role:"It forages for small invertebrates in sand and crevices at night, contributing to the reef's nutrient recycling."},
{id:"spotted-drum", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Equetus_punctatus_juvenile.jpg", name:"Spotted Drum", size:"8–10 in",
  desc:"Juveniles have a long trailing fin and swim with an odd swaying motion; adults develop bold black-and-white spots and stripes.",
  role:"It picks small invertebrates from crevices at night and its swaying juvenile display is thought to mimic a flatworm to avoid predators, an example of the reef's many defensive strategies."},
{id:"atlantic-spadefish", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Chaetodipterus_faber_Gratwicke.jpg", name:"Atlantic Spadefish", size:"1–2 ft",
  desc:"A silver, disc-shaped fish with bold vertical black bars, often seen in large schools swirling around wrecks and reef structure.",
  role:"It feeds on jellyfish, small invertebrates, and plankton, helping keep jellyfish blooms in check around Keys reefs and wrecks."},
{id:"spotted-eagle-ray", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Aetobatus_narinari_(spotted_eagle_ray)_(Bimini%2C_western_Bahamas)_(15966477698).jpg", name:"Spotted Eagle Ray", size:"6–10 ft wingspan",
  desc:"A graceful ray covered in white spots, often seen 'flying' through open water or leaping clear of the surface.",
  role:"It digs through sand for clams and other buried shellfish, and this constant digging aerates and turns over the sea floor, much like an earthworm does on land."},
{id:"yellow-jack", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Caranx_bartholomaei%2C_avistamento_S%25C3%25A3o_Vicente_e_Granadinas.jpg", name:"Yellow Jack", size:"1–2 ft",
  desc:"A fast, silvery open-water fish with a yellowish tail, often seen cruising reef edges in small fast-moving groups.",
  role:"As an active mid-water predator, it chases down smaller schooling fish, keeping baitfish populations moving and in check."},
{id:"bar-jack", cat:"fish", name:"Bar Jack", size:"1–2 ft",
  desc:"Recognized by a dark stripe running from its dorsal fin down through its tail, it's a fast hunter often seen shadowing larger animals like rays to snap up disturbed prey.",
  role:"It follows stingrays and other bottom-feeders to grab small prey stirred up from the sand, linking different feeding strategies together on the reef."},
{id:"yellow-goatfish", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Mulloidichthys_martinicus.jpg", name:"Yellow Goatfish", size:"8–11 in",
  desc:"A silvery fish with a yellow stripe and a pair of chin barbels used to feel and taste for prey buried in sand.",
  role:"By stirring sand with its barbels to find food, it aerates the sea floor and exposes buried invertebrates that other fish then feed on too."},
{id:"spotted-goatfish", cat:"fish", name:"Spotted Goatfish", size:"9–12 in",
  desc:"Pale with three dark saddle blotches, it uses its chin barbels to probe sand for hidden prey, much like the yellow goatfish.",
  role:"Its constant sand-probing turns over the sea floor and flushes out small invertebrates, benefiting other sand-dwelling reef fish."},
{id:"porcupinefish", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Spot-fin_porcupinefish_(Diodon_hystrix)_(27597460948).jpg", name:"Porcupinefish", size:"1–2 ft", spotted:true,
  desc:"A relative of the pufferfish covered in sharp spines that stand upright when it inflates with water to deter predators.",
  role:"It has strong crushing teeth for cracking snail shells and crab shells, helping keep hard-shelled invertebrate populations in check."},
{id:"yellow-stingray", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Urobatis_jamaicensis.jpg", name:"Yellow Stingray", size:"1–2 ft",
  desc:"A round, patterned ray that buries itself in sand with only its eyes exposed, waiting to ambush prey.",
  role:"It preys on small fish and invertebrates buried in the sand, and its digging helps aerate sandy bottom habitat near the reef."},
{id:"southern-stingray", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Southern_Stingray_Dasyatis_Americana_(227919279).jpeg", name:"Southern Stingray", size:"4–6 ft wingspan",
  desc:"A large, diamond-shaped ray that glides just above the sand, using electrical sensors in its snout to find buried prey.",
  role:"Its digging for clams and worms turns over huge amounts of sand each year, which is a major way sediment gets aerated and mixed on Keys flats."},
{id:"green-moray", cat:"fish", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Green_Moray_Eel_(Gymnothorax_funebris)%2C_Cozumel.jpg", name:"Green Moray Eel", size:"5–8 ft",
  desc:"Actually brown-skinned, it looks green because of a yellow mucus coating over its skin; it constantly opens and closes its mouth to pump water over its gills, not to threaten.",
  role:"As a nighttime ambush predator hiding in reef crevices, it controls populations of fish, octopus, and crustaceans that shelter in the same holes."},

/* ============ SHELLS & MOLLUSKS ============ */
{id:"queen-conch", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Queen_Conch_(Lobatus_gigas).jpg", name:"Queen Conch", size:"6–12 in", spotted:true,
  desc:"A large sea snail with a flared, pink-lipped shell, once so common in the Keys it's now protected after decades of overharvesting.",
  role:"As a grazer of algae and seagrass detritus, the queen conch helps keep seagrass meadows clean, and its shell (after death) becomes habitat for smaller creatures."},
{id:"horse-conch", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Triplofusus_giganteus_(Florida_horse_conch)_2_(24484045126).jpg", name:"Horse Conch", size:"up to 24 in", spotted:true,
  desc:"Florida's state shell and the largest sea snail in North America, with bright orange flesh inside a dark, spiky shell.",
  role:"It's an active predator of other snails, including queen conchs, so it plays an important role keeping snail populations from over-grazing seagrass beds."},
{id:"scotch-bonnet", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Semicassis_granulata_granulata_01.JPG", name:"Scotch Bonnet", size:"3 in", spotted:true,
  desc:"A round, cream-colored shell with a pattern resembling tartan plaid, found buried in sand during the day.",
  role:"It preys on sand dollars and sea biscuits, helping keep those populations from overwhelming sandy flats near the reef."},
{id:"florida-fighting-conch", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Strombus_alatus_(fighting_conch)_(Marco_Island%2C_Florida%2C_USA)_4.jpg", name:"Florida Fighting Conch", size:"3 in", spotted:true,
  desc:"A smaller, smooth-shelled relative of the queen conch, named for the way it flips and 'kicks' with its foot when handled.",
  role:"It grazes on algae and detritus in seagrass beds, helping keep those meadows healthy and free of excess algae buildup."},
{id:"queen-helmet", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Cassis_madagascariensis_(emperor_helmet_snail)_1_(24383291282).jpg", name:"Queen Helmet", size:"up to 11 in",
  desc:"One of the largest and heaviest Florida shells, with a thick, glossy shell and a wide toothed outer lip.",
  role:"Like other helmet shells, it's a predator of sea urchins and sand dollars, helping keep spiny grazer populations from overrunning the sea floor."},
{id:"bubble-shell", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Bulla_striata_01.JPG", name:"Bubble Shell", size:"1.5 in",
  desc:"A thin, fragile, rounded shell belonging to a sea slug relative that partially retreats inside it for protection.",
  role:"These small mollusks graze algae and organic matter on the sea floor, contributing to the reef's nutrient recycling at a very small scale."},
{id:"deer-cowrie", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Atlantic_Deer_Cowry_(11670898834).jpg", name:"Deer Cowrie", size:"up to 7 in",
  desc:"A large, glossy cowrie covered in brown spots resembling a deer's coat, with a smooth, egg-shaped shell.",
  role:"At night it grazes algae and sponges off rocks and coral rubble, and its glossy shell protects a soft mantle that can fully cover the shell while it feeds."},
{id:"cowrie-helmet", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Cypraecassis_testiculus_(Linnaeus%2C_1758)_2013_000.JPG", name:"Cowrie Helmet", size:"2 in",
  desc:"A small, sturdy shell with a toothed opening, sharing traits of both cowrie and helmet shell families.",
  role:"It preys on small invertebrates on the sea floor, contributing to the balance of tiny grazing animals near the reef base."},
{id:"common-nutmeg", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Cancellaria_reticulata.JPG", name:"Common Nutmeg", size:"1.5 in",
  desc:"A ribbed, cream-and-brown shell shaped a bit like the spice it's named for, usually found in sand near seagrass beds.",
  role:"It's a scavenger and small predator on the sea floor, helping clean up organic debris in seagrass habitats."},
{id:"measled-cowrie", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Macrocypraea_zebra_(measled_cowrie)_2_(24428413944).jpg", name:"Measled Cowrie", size:"1–3.5 in",
  desc:"Named for the tiny dark spots covering its shell like a measles rash, it hides under rocks and rubble by day.",
  role:"It grazes algae and sponges at night, helping control those growths on rocky reef rubble."},
{id:"doe-cowrie", cat:"shells", name:"Doe Cowrie", size:"1 in",
  desc:"A small, glossy cowrie with fine speckling, closely related to the larger deer cowrie but smaller and more delicate.",
  role:"Like other cowries, it grazes algae from rock and rubble surfaces, keeping those surfaces open for coral larvae to settle."},
{id:"apple-murex", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Phyllonotus_pomum_01.JPG", name:"Apple Murex", size:"3 in",
  desc:"A spiny, rounded shell resembling an apple, colored in bands of brown, orange, and cream.",
  role:"Murex snails drill through the shells of clams and other bivalves to eat them, helping control bivalve populations on sandy and reef bottoms."},
{id:"florida-rock-shell", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Stramonita_haemastoma_01.JPG", name:"Florida Rock Shell", size:"2 in",
  desc:"A rough, spiky whelk that clings to rocks and pilings in the intertidal zone, where waves crash regularly.",
  role:"It preys on barnacles and small mussels attached to rocks, keeping those crowded rock-dwelling communities in balance."},
{id:"bleeding-tooth", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Nerita_peloronta_(bleeding_tooth_nerite_snail)_(San_Salvador_Island%2C_Bahamas)_2.jpg", name:"Bleeding Tooth Nerite", size:"1 in",
  desc:"A small, colorful shell with red-orange marks around its opening that look like blood around its teeth, found on rocks right at the waterline.",
  role:"It grazes algae films off rocks in the splash zone, keeping intertidal rocks from becoming overgrown and slick."},
{id:"cabrits-murex", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Cabrit's_Murex_(11405170393).jpg", name:"Cabrit's Murex", size:"2 in",
  desc:"A delicate, spiny murex shell with long, frilly spines radiating outward from its whorls.",
  role:"Like other murex snails, it drills into and preys on small bivalves, helping regulate those populations in sandy habitats."},
{id:"crown-conch", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Melongena_corona_4.jpg", name:"Crown Conch", size:"3–4 in",
  desc:"A banded shell with a ring of spiky knobs around its widest whorl, resembling a crown, commonly found near mangrove shorelines.",
  role:"It's a scavenger and predator of oysters and other bivalves in brackish mangrove habitats, helping recycle nutrients along the shoreline."},
{id:"lace-murex", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Lace_Murex_(11358231083).jpg", name:"Lace Murex", size:"2 in",
  desc:"A delicate shell with frilly, lace-like spines that make it look far more fragile than it actually is.",
  role:"It drills into small bivalves and barnacles to feed, contributing to the natural turnover of those populations near the reef."},
{id:"gaudy-natica", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Naticarius_canrena_(colorful_Atlantic_moon_snail)_2_(24965730641).jpg", name:"Gaudy Natica (Moon Snail)", size:"1.5 in",
  desc:"A rounded, glossy shell that plows just beneath the sand surface, leaving a visible trail, in search of buried prey.",
  role:"It drills perfectly round holes into clams to eat them, and empty moon snail shells become homes for hermit crabs afterward."},
{id:"pink-conch", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Strombus_gigas_(queen_conch)_3_(25058998465).jpg", name:"Pink (Queen) Conch", size:"up to 8 in",
  desc:"Another name used for the queen conch's shell, prized for its bright pink flared lip once the snail is fully grown.",
  role:"See Queen Conch — this grazing snail keeps seagrass meadows clear of excess algae and detritus."},
{id:"sharks-eye", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Neverita_duplicata_01.JPG", name:"Shark's Eye Moon Snail", size:"2.5 in", spotted:true,
  desc:"A smooth, round shell with a dark spiral center that resembles a shark's eye, found plowing through sand for prey.",
  role:"Like other moon snails, it drills into clams to feed, and its empty shell often becomes a hermit crab's new home."},
{id:"common-fig-shell", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Ficus_gracilis_01.JPG", name:"Common Fig Shell", size:"3 in",
  desc:"A thin, lightweight, fig-shaped shell with fine ridges, found in sandy areas near seagrass.",
  role:"It preys on sea urchins and other echinoderms, helping keep those populations from overgrazing sandy and reef-edge habitats."},
{id:"slipper-shell", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Crepidula_fornicata_(common_Atlantic_slipper_snail)_(Marco_Island%2C_Florida%2C_USA)_1.jpg", name:"Slipper Shell", size:"1.5 in",
  desc:"A flattened, boat-shaped shell that lives attached to rocks or other shells and changes sex from male to female as it grows.",
  role:"As a filter feeder, it strains plankton from the water, and it often lives stacked on other shells, adding structure for other tiny creatures."},
{id:"florida-worm-shell", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Vermicularia_knorrii_(Florida_worm_snail_shells)_(Sanibel_Island%2C_Florida%2C_USA)_1_(49762451528).jpg", name:"Florida Worm Shell", size:"4 in", spotted:true,
  desc:"A snail with a shell so irregularly coiled it looks like a tangle of tube worms rather than a typical spiral shell.",
  role:"It cements itself to rock and filters plankton or traps food in mucus strands, and its tangled shells add complex hiding structure for small reef creatures."},
{id:"tinted-cantharus", cat:"shells", name:"Tinted Cantharus", size:"1 in",
  desc:"A small, sturdy whelk with a ribbed shell in muted brown and cream tones, found among rocks and rubble.",
  role:"It scavenges dead animal matter on the sea floor, helping clean up organic debris around the reef base."},
{id:"sundial-shell", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Architectonica_maxima_01.JPG", name:"Sundial Shell", size:"1.5 in",
  desc:"A flattened, perfectly spiraled shell with a wide central opening, patterned in fine concentric rings like a sundial.",
  role:"It preys on anemones and other soft-bodied invertebrates, an unusual diet that helps control those populations near the reef."},
{id:"babys-ear", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Sinum_perspectivum_01.JPG", name:"Baby's Ear Moon Snail", size:"1.5 in",
  desc:"A very flat, ear-shaped shell, one of the flattest moon snails found in Florida waters.",
  role:"Like other moon snails, it hunts clams beneath the sand, helping regulate bivalve populations on sandy flats."},
{id:"florida-cerith", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Cerithium_lutosum_02.JPG", name:"Florida Cerith", size:"1 in",
  desc:"A small, tightly-spiraled, tower-shaped shell commonly found grazing on seagrass blades and sand.",
  role:"It grazes algae film off seagrass blades and sand, helping keep seagrass surfaces clean so the grass can photosynthesize efficiently."},
{id:"american-auger", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Terebra_dislocata_(common_American_auger_snail_shell)_(Sanibel_Island%2C_Florida%2C_USA)_2_(49772174158).jpg", name:"American Auger", size:"2.5 in",
  desc:"A long, narrow, drill-bit-shaped shell that burrows quickly through sand in search of prey.",
  role:"It hunts small worms buried in sand, helping keep worm populations balanced on sandy flats near the reef."},
{id:"caribbean-vase", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Vasum_turbinellus_01.JPG", name:"Caribbean Vase", size:"3 in",
  desc:"A thick, heavy shell with knobby spines and a vase-like shape, found in sand and rubble near seagrass.",
  role:"It's a predator of small bivalves and worms, helping regulate those populations in seagrass-adjacent sandy habitat."},
{id:"common-dove-shell", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Columbella_mercatoria_01.JPG", name:"Common Dove Shell", size:"0.5 in",
  desc:"A tiny, smooth, glossy shell found in large numbers among rubble and seagrass wrack.",
  role:"It scavenges algae and organic debris, playing a small but important part in recycling nutrients at the base of the food web."},
{id:"long-spined-star-shell", cat:"shells", name:"Long-spined Star Shell", size:"2 in",
  desc:"A spiky, star-shaped shell covered in long projecting spines, giving it an intimidating look for its small size.",
  role:"It grazes algae from rock and rubble surfaces, helping keep those hard surfaces clear for coral larvae to settle on."},
{id:"chestnut-turban", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Turbo_castanea_002.jpg", name:"Chestnut Turban", size:"1 in",
  desc:"A rounded, ridged shell in warm chestnut-brown tones, sealed with a hard trapdoor called an operculum when the snail retreats inside.",
  role:"It grazes algae off rock and rubble, and its hard trapdoor lets it survive being tumbled by waves in shallow rocky habitat."},
{id:"jujube-top-shell", cat:"shells", name:"Jujube Top Shell", size:"1 in",
  desc:"A colorful, cone-shaped shell with a pearly, iridescent underside once the outer layer wears away.",
  role:"It grazes algae from rocks and seagrass, contributing to the overall grazing pressure that keeps reef-adjacent surfaces clean."},
{id:"american-star-shell", cat:"shells", name:"American Star Shell", size:"1.5 in",
  desc:"A rounded, knobby shell in the turban family, often encrusted with algae and small growths that camouflage it.",
  role:"It grazes algae from rocky and rubble surfaces, adding to the community of grazers that keep hard substrate clear."},
{id:"junonia", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Scaphella_junonia.jpg", name:"Junonia", size:"3.5 in",
  desc:"One of the rarest and most prized Florida shells, with a pattern of square brown spots on a cream background.",
  role:"It's a deep-water predator of other small mollusks; because it lives offshore in deeper water, finding one washed ashore is a rare event."},
{id:"lettered-olive", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Oliva_sayana_02.JPG", name:"Lettered Olive", size:"3 in",
  desc:"Florida's official state shell, smooth and glossy with squiggly brown markings resembling handwriting.",
  role:"It burrows through sand hunting small clams and worms, and its constant plowing helps aerate sandy sea floor habitat."},
{id:"giant-tun", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Tonna_galea_01.jpg", name:"Giant Tun", size:"up to 7 in",
  desc:"A large, thin-shelled, barrel-shaped snail with a huge body relative to its shell size.",
  role:"It preys on sea cucumbers, one of the few predators willing to eat them, helping keep sea cucumber populations in check."},
{id:"common-carrier-shell", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Xenophora_conchyliophora_(Atlantic_carrier_snail)_8_(24654769506).jpg", name:"Common Carrier Shell", size:"2 in",
  desc:"A remarkable snail that cements shell fragments, coral bits, and rocks onto its own shell as camouflage and armor.",
  role:"By 'recycling' broken shell debris onto itself, it disguises itself from predators while also creating tiny mobile habitat patches for hitchhiking organisms."},
{id:"violet-snail", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Janthina_janthina_01.JPG", name:"Violet Snail", size:"1.5 in",
  desc:"A delicate purple sea snail that builds its own raft of bubbles to float upside-down at the ocean's surface.",
  role:"It drifts on the open ocean feeding on Portuguese man-of-war and other floating jellies, helping control those stinging drifters."},
{id:"nerite-snail", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Nerita_versicolor_(four-toothed_nerite_snails)_in_a_rocky_shore_intertidal_zone_(San_Salvador_Island%2C_Bahamas)_9_(16013609451).jpg", name:"Nerite Snail", size:"0.5–1 in", spotted:true,
  desc:"A group of small, sturdy, patterned shells (including four-tooth, three-tooth, and bleeding tooth varieties) found clustered on rocks at the waterline.",
  role:"Nerites graze algae films off rocks in the intertidal zone, an important job that keeps shoreline rocks from becoming slick and overgrown."},
{id:"periwinkle-snail", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Echinolittorina_ziczac_2.jpg", name:"Periwinkle Snail", size:"0.5 in", spotted:true,
  desc:"A tiny, cone-shaped snail found in huge numbers climbing mangrove roots and rocks just above the waterline.",
  role:"It grazes algae and fungus off mangrove roots and bark, and in turn is an important food source for shorebirds and crabs."},
{id:"turban-snail", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Cittarium_pica_01.JPG", name:"Turban Snail", size:"1 in", spotted:true,
  desc:"A rounded, spiral shell often found grazing on long mangrove algae strands near prop roots.",
  role:"It grazes algae growing on mangrove roots, helping keep those roots from being smothered while feeding shoreline food chains."},
{id:"tulip-snail", cat:"shells", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Fasciolaria_tulipa_01.JPG", name:"Tulip Snail", size:"2–4 in", spotted:true,
  desc:"A smooth, colorfully banded shell shaped like a tulip flower, an active hunter that moves quickly for a snail.",
  role:"It's an aggressive predator of other snails and bivalves, including ones larger than itself, helping keep mollusk populations balanced."},

/* ============ INVERTEBRATES & OTHER SEA LIFE ============ */
{id:"hawksbill-turtle", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Hawksbill_sea_turtle_-_NOAA.jpg", name:"Hawksbill Sea Turtle", size:"2.5–3 ft shell", spotted:true,
  desc:"Named for its narrow, hawk-like beak, this critically endangered turtle has a sharp beak built for reaching into reef crevices.",
  role:"Hawksbills eat sponges that would otherwise outcompete slow-growing corals for space, making them essential to keeping coral reefs from being smothered."},
{id:"lettuce-sea-slug", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Lettuce_Sea_Slug_11-03-2006.jpg", name:"Lettuce Sea Slug", size:"2–3 in",
  desc:"A ruffled, leafy-green sea slug that steals working chloroplasts from the algae it eats and uses them to photosynthesize like a plant.",
  role:"By 'farming' light this way it needs to eat less, reducing grazing pressure on the algae it feeds on compared to typical grazers."},
{id:"common-octopus", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Octopus_vulgaris_02.JPG", name:"Common Octopus", size:"1–3 ft arm span",
  desc:"A highly intelligent, soft-bodied predator that can change color and texture instantly to vanish against the reef.",
  role:"As both hunter and hunted, the octopus preys on crabs and shellfish while being a key food source for sharks, eels, and groupers on the reef."},
{id:"banded-coral-shrimp", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Stenopus_hispidus.jpg", name:"Banded Coral Shrimp", size:"2 in",
  desc:"A striking red-and-white striped shrimp with long white antennae, usually seen in pairs waving from reef crevices.",
  role:"It runs a 'cleaning station,' picking parasites and dead skin off fish that line up to be serviced, directly improving the health of reef fish."},
{id:"deepwater-gorgonia", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Iciligorgia_schrammi.jpg", name:"Deepwater Gorgonian", size:"up to 3 ft",
  desc:"A branching soft coral with a flexible, tree-like skeleton that sways with the current instead of standing rigid like hard coral.",
  role:"Its branches provide shelter and hunting perches for small fish, shrimp, and brittle stars, adding structure to otherwise open reef sections."},
{id:"moon-jellyfish", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Moon_jellyfish_at_Gota_Sagher.JPG", name:"Moon Jellyfish", size:"10–16 in",
  desc:"A translucent, saucer-shaped jelly with four visible horseshoe-shaped rings, and only a mild sting compared to other jellies.",
  role:"It feeds on plankton and fish larvae, and in turn is one of the main foods of sea turtles, linking plankton blooms to larger reef visitors."},
{id:"portuguese-man-of-war", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Portuguese_Man-O-War_(Physalia_physalis).jpg", name:"Portuguese Man-of-War", size:"up to 30 ft tentacles",
  desc:"Not a true jellyfish but a colony of specialized organisms working together, with a gas-filled float on the surface and powerful stinging tentacles below.",
  role:"It preys on small fish and plankton at the surface, and its floats are eaten by violet snails and loggerhead turtles, some of its few predators."},
{id:"stinging-jellyfish", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Compass_Jellyfish_(Chrysaora_hysoscella).jpg", name:"Atlantic Sea Nettle", size:"6–8 in bell",
  desc:"A pale, translucent jelly with long trailing tentacles and a noticeable, though not dangerous, sting.",
  role:"It preys on small fish larvae and zooplankton, and its blooms are an important food source for sea turtles passing through the Keys."},
{id:"upside-down-jellyfish", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Upside-down_jellyfish_(Cassiopea_xamachana).jpg", name:"Upside-down Jellyfish", size:"6–12 in",
  desc:"Instead of swimming, it rests bell-down on the sea floor with frilly arms facing up toward the sun, like an underwater plant.",
  role:"Algae living inside its tissue photosynthesize for it, similar to coral, and its stinging mucus released into the water can stun tiny prey nearby."},
{id:"reef-squid", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Caribbean_reef_squid.jpg", name:"Caribbean Reef Squid", size:"6–8 in",
  desc:"A fast, intelligent squid that can flash rippling color patterns across its skin to communicate or startle predators.",
  role:"It's an important mid-water predator of small fish and shrimp, and a major food source itself for larger fish, squid, and dolphins."},
{id:"scarlet-cleaner-shrimp", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Lysmata_grabhami.jpg", name:"Scarlet Cleaner Shrimp", size:"1–2 in",
  desc:"A bright red-and-white striped shrimp with long white antennae that advertises its cleaning services to passing fish.",
  role:"It removes parasites, dead tissue, and food scraps from fish mouths and gills, directly reducing disease and parasite loads on the reef."},
{id:"spotted-cleaner-shrimp", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Spotted_cleaner_shrimp_(Periclimenes_yucatanicus)_-_Harry's_Hole_Reef%2C_Soto%2C_Cura%25C3%25A7ao_Netherland_Antilles.jpg", name:"Spotted Cleaner Shrimp", size:"1 in",
  desc:"A translucent shrimp with purple-spotted markings that often lives in a partnership with sea anemones for protection.",
  role:"Like other cleaner shrimp, it picks parasites off reef fish, and its anemone partnership shows how species team up for mutual protection."},
{id:"sea-whip", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Pseudopterogorgia_americana.jpg", name:"Sea Whip", size:"up to 6 ft",
  desc:"A thin, unbranched soft coral that grows in a single tall whip shape, swaying with the current.",
  role:"It provides a perch for tiny gobies, brittle stars, and shrimp, adding vertical structure to sand and rubble areas near the reef."},
{id:"giant-caribbean-anemone", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Condylactis_gigantea_(Giant_Anemone)_red_base.jpg", name:"Giant Caribbean Anemone", size:"1 ft across",
  desc:"A large anemone with long, thin tentacles tipped in purple or pink, anchored into reef crevices or sand.",
  role:"It hosts cleaner shrimp and other partner species among its stinging tentacles, offering them protection in exchange for food scraps and cleaning."},
{id:"sea-plume", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Pseudopterogorgia_sp.jpg", name:"Sea Plume", size:"up to 6 ft",
  desc:"A feathery, branching soft coral related to sea fans, forming dense purple or tan colonies that wave in the current.",
  role:"Like other gorgonians, it adds three-dimensional structure to the reef, sheltering small fish and invertebrates among its branches."},
{id:"feather-duster-worm", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Sabellidae_(feather_duster_worm).jpg", name:"Feather Duster Worm", size:"2–4 in",
  desc:"A tube-dwelling worm with a colorful, feathery crown of tentacles that instantly retracts into its tube if disturbed.",
  role:"It filters plankton and organic particles from the water with its feathery crown, helping keep reef water clear."},
{id:"fire-worm", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Bearded_fireworm_(Hermodice_carunculata).jpg", name:"Fire (Bristle) Worm", size:"2–6 in",
  desc:"A segmented worm covered in fine white bristles that can break off in skin and cause a painful, burning sting if touched.",
  role:"It scavenges dead coral tissue and soft-bodied invertebrates, acting as one of the reef's cleanup crew."},
{id:"christmas-tree-worm", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Spirobranchus_giganteus_(assorted_Christmas_tree_worms).jpg", name:"Christmas Tree Worm", size:"1.5 in",
  desc:"A tiny tube worm that bores into living coral and extends two spiral, tree-shaped crowns to filter feed, vanishing instantly when disturbed.",
  role:"It filters plankton from the water and, though it lives inside coral, generally doesn't harm its host, showing how reef organisms can share space closely."},
{id:"star-horseshoe-worm", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Pomatostegus_stellatus_(Star_Horseshoe_Worm).jpg", name:"Star Horseshoe Worm", size:"2–3 in",
  desc:"A tube worm with a spiraled, star-like crown of tentacles in orange and white, found on rock and reef rubble.",
  role:"Like other tube worms, it filters plankton from the water column, contributing to overall water clarity around the reef."},
{id:"red-wall-sponge", cat:"other", name:"Red Encrusting Sponge", size:"varies",
  desc:"A thin, bright red sponge that spreads flat across rock and reef surfaces like a coat of paint.",
  role:"Sponges filter enormous volumes of water daily, and this one recycles nutrients back into the reef while providing camouflage for small crabs and shrimp."},
{id:"yellow-tube-sponge", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Aplysina_fistularis_(Yellow_Tube_Sponge).jpg", name:"Yellow Tube Sponge", size:"up to 5 ft",
  desc:"A cluster of bright yellow, hollow tubes that can grow to impressive heights on the reef.",
  role:"Each tube filters huge volumes of seawater daily, removing bacteria and particles, and its tubes shelter small fish and shrimp."},
{id:"corky-sea-fingers", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Corky_Sea_Fingers_on_the_Fathom.JPG", name:"Corky Sea Fingers", size:"1–2 ft",
  desc:"A soft coral with thick, finger-like branches and a rough, cork-textured surface, common on shallow reef flats.",
  role:"It adds structural complexity to shallow reef areas, giving small reef creatures places to hide among its branches."},
{id:"sea-rod", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Black_sea_rod_Plexaura_homomalla_(4675579531).jpg", name:"Purple Sea Rod", size:"1–3 ft",
  desc:"A branching soft coral with smooth purple or lavender branches, common across Keys reefs.",
  role:"Its branching structure shelters brittle stars, shrimp, and small fish, adding vertical habitat to the reef."},
{id:"branching-tube-sponge", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Pseudoceratina_crassa_(Branching_Tube_Sponge-_yellow%2526purple_variation).jpg", name:"Branching Tube Sponge", size:"1–3 ft",
  desc:"A sponge that grows in clusters of narrow, branching blue-grey tubes rising from the reef.",
  role:"Like other sponges, it filters water constantly, and its tube clusters create shelter for gobies and small crustaceans."},
{id:"white-encrusting-zoanthid", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Mat_zoanthid_or_rubber_coral%2C_Palythoa_tuberculosa%2C_which_is_highly_toxic%2C_producing_one_of_the_most_toxic_non-peptide_substances_known._The_toxin_is_produced_by_symbiotic_bacteria._(6163182467).jpg", name:"White Encrusting Zoanthid", size:"varies",
  desc:"A colonial soft coral relative that forms dense mats of small, flower-like polyps over rock and rubble.",
  role:"It competes for space with algae and sponges, and its dense mats stabilize loose rubble on shallow reef flats."},
{id:"common-sea-fan", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Common_sea_fan_Gorgonia_ventalina_(4676539477).jpg", name:"Common (Purple) Sea Fan", size:"up to 6 ft",
  desc:"A flat, fan-shaped soft coral that grows perpendicular to the current so it can catch drifting plankton efficiently.",
  role:"Its broad fan shape shelters flamingo tongue snails, brittle stars, and tiny gobies, making it one of the busiest microhabitats on the reef."},
{id:"venus-sea-fan", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Gorgonia_flabellum_(Venus_seafan)_(San_Salvador_Island%2C_Bahamas)_4_(16065970756).jpg", name:"Venus Sea Fan", size:"up to 3 ft",
  desc:"A finer, more delicate lattice-patterned sea fan than the common sea fan, usually found in shallower water.",
  role:"Like other sea fans, it provides shelter and feeding perches for small reef animals while filtering plankton from passing currents."},
{id:"blue-bell-tunicate", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Clavelina_puertosecensis_169478752.jpg", name:"Blue Bell Tunicate", size:"0.5 in per bell",
  desc:"A cluster of tiny, translucent blue, bell-shaped filter feeders that grow in connected colonies on rock and rubble.",
  role:"Tunicates filter bacteria and fine particles from the water, contributing to overall water clarity around the reef."},
{id:"orange-wall-sponge", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Orange_wall_sponge_at_Partridge_Point_P7190515.JPG", name:"Orange Wall Sponge", size:"varies",
  desc:"A thick, lumpy orange sponge that forms mounds or coats reef walls and ledges.",
  role:"It filters seawater and provides bright camouflage and shelter for small crabs and brittle stars living within its folds."},
{id:"brown-encrusting-sponge", cat:"other", name:"Brown Encrusting Sponge", size:"varies",
  desc:"A rough, mustard-brown sponge that spreads in irregular patches across dead coral and rock.",
  role:"It filters water and, notably, some encrusting sponges can slowly bore into coral skeletons, recycling old reef structure over time."},
{id:"arrow-crab", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Stenorhynchus_seticornis_(Yellowline_Arrow_Crab).jpg", name:"Arrow Crab", size:"2 in body, long legs",
  desc:"A spindly crab with an arrow-shaped body and extremely long, thin legs, usually seen at night among rubble and anemones.",
  role:"It scavenges algae and small invertebrates, and is known to eat bristle worms, helping control that stinging species on the reef."},
{id:"slate-pencil-urchin", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Eucidaris_tribuloides_(Slate-pencil_Urchin).jpg", name:"Slate Pencil Urchin", size:"3–4 in",
  desc:"An urchin with thick, blunt, pencil-like spines instead of the thin sharp spines most urchins have.",
  role:"It grazes algae from rock and rubble at night, and its sturdy spines let it wedge into wave-battered crevices other urchins can't use."},
{id:"long-spined-sea-urchin", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Long_Spiny_Sea_Urchin_(Diadema_antillarum_(Philippi)_(2863775301).jpg", name:"Long-spined Sea Urchin", size:"spines up to 12 in",
  desc:"Covered in dangerously sharp, needle-thin black spines, this urchin was nearly wiped out by disease in the 1980s across the Caribbean.",
  role:"It's one of the reef's most important algae grazers — when its population crashed from disease, algae overgrew and smothered huge areas of Caribbean coral, showing just how critical this species is."},
{id:"azure-vase-sponge", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Callyspongia_plicifera_(Azure_Vase_Sponge).jpg", name:"Azure Vase Sponge", size:"1–2 ft",
  desc:"A striking purple-blue, vase-shaped sponge that stands upright on the reef, easily one of the most photographed sponges in the Keys.",
  role:"Its wide vase shape filters large volumes of water, and its inner cup shelters small shrimp and brittle stars from predators."},
{id:"coral-crab", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Carpilius_corallinus_(batwing_coral_crab)_(San_Salvador_Island%2C_Bahamas)_1_(16144117235).jpg", name:"Coral (Batwing) Crab", size:"3–4 in",
  desc:"A smooth-shelled, brightly patterned crab that lives tucked among coral heads and rock crevices.",
  role:"It scavenges algae and detritus around coral heads, helping keep coral surfaces free of buildup that could smother the polyps."},
{id:"spanish-slipper-lobster", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Slipper_lobster.jpg", name:"Spanish (Slipper) Lobster", size:"1 ft",
  desc:"A flattened lobster relative with no claws, instead using wide, shovel-like antennae plates to dig and defend itself.",
  role:"As a scavenger and predator of small mollusks, it helps recycle dead organic matter on the reef floor at night."},
{id:"spiny-spider-crab", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Mithrax_spinosissimus_(Channel_Clinging_Crab_-_female).jpg", name:"Spiny (Decorator) Spider Crab", size:"1–4 in body", spotted:true,
  desc:"A slow-moving crab covered in hooked bristles that it uses to attach algae, sponge, and debris to its shell as living camouflage.",
  role:"By 'decorating' itself with algae and sponge, it disguises itself from predators while also spreading those organisms to new patches of reef as it moves."},
{id:"thorny-oyster", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Spondylus_americanus_Hermann%2C_1781_2013_002.JPG", name:"Thorny Oyster", size:"4–6 in",
  desc:"A bivalve covered in long, spiky projections that collect algae and sponge growth, camouflaging it against the reef.",
  role:"As a filter feeder cemented in place, it cleans large volumes of water and its spines provide anchor points for tiny hitchhiking organisms."},
{id:"red-thorny-sea-star", cat:"other", name:"Red Thorny Sea Star", size:"4–6 in", spotted:true,
  desc:"A dark red sea star covered in short, blunt spines, usually found tucked under rocks and rubble by day.",
  role:"It scavenges algae and organic debris off the seafloor, playing a small role in cleaning up detritus around the reef base."},
{id:"caribbean-spiny-lobster", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Panulirus_argus_(Caribbean_spiny_lobster)_(San_Salvador_Island%2C_Bahamas)_2_(16144042375).jpg", name:"Caribbean Spiny Lobster", size:"1–1.5 ft",
  desc:"Unlike Maine lobsters, it has no large front claws, instead relying on long spiny antennae and speed to escape predators.",
  role:"It's a keystone scavenger, eating dead animal matter and snails on the reef, and is itself an important food source for sharks, octopus, and groupers."},
{id:"giant-hermit-crab", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Giant_Hermit_Crab_(11670683275).jpg", name:"Giant Hermit Crab", size:"up to 6 in body",
  desc:"One of the largest hermit crabs in the Atlantic, it commandeers the largest available shells, often queen conch or horse conch shells.",
  role:"As a scavenger, it cleans up dead organic matter on the sea floor, and its need for large shells creates demand that keeps a market of empty shells cycling between hermit crabs of all sizes."},
{id:"red-reef-hermit-crab", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Paguristes_cadenati.jpg", name:"Red Reef Hermit Crab", size:"1 in body",
  desc:"A small, colorful hermit crab with red-and-white banded legs, commonly found scuttling across reef rubble in borrowed snail shells.",
  role:"It scavenges algae and detritus on the reef, and recycles empty snail shells as portable homes, cycling those shells through the ecosystem."},
{id:"cushion-sea-star", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Oreaster_reticulatus201905mx.jpg", name:"Cushion Sea Star", size:"up to 1 ft",
  desc:"A thick, puffy, five-armed sea star in warm orange-brown tones, often found partly buried in sand near seagrass.",
  role:"It grazes algae, detritus, and small invertebrates from the sand and seagrass, helping keep those habitats clean."},
{id:"spider-crab", cat:"other", name:"Spider Crab", size:"2–4 in body", spotted:true,
  desc:"A slow, long-legged crab covered in fine hooked hairs that it uses to attach bits of algae and sponge for camouflage.",
  role:"Like its decorator crab relatives, it grazes algae and scavenges debris while disguising itself among the reef rubble it lives in."},
{id:"banded-brittle-star", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/Ophioderma_longicaudum_(Bruzelius%2C_1805).jpg", name:"Banded Brittle Star", size:"arms up to 6 in", spotted:true,
  desc:"A fast-moving relative of sea stars with long, thin, spiny arms that can detach and regrow if grabbed by a predator.",
  role:"It scavenges tiny organic particles from crevices and coral, and its constant movement through reef nooks helps stir and recycle debris."},
{id:"donkey-dung-sea-cucumber", cat:"other", name:"Donkey Dung Sea Cucumber", size:"8–14 in", spotted:true,
  desc:"A large, dark, oblong sea cucumber that moves slowly across sand and seagrass, vacuuming up sediment as it goes.",
  role:"It swallows sand and digests the organic material within it, then excretes cleaned sand — a single sea cucumber can process tons of sea floor sediment a year, keeping it healthy and oxygenated."},
{id:"urchin-skeleton", cat:"other", img:"https://commons.wikimedia.org/wiki/Special:FilePath/White_sea_urchin.jpg", name:"Sea Urchin Test (Skeleton)", size:"1–4 in",
  desc:"The hard, rounded shell (called a test) left behind after a sea urchin dies, often bleached white and found on beaches.",
  role:"In life, urchins are major algae grazers whose feeding keeps coral surfaces clear; their tests also add calcium carbonate back into the sand over time."},
{id:"decorator-crab-skeleton", cat:"other", name:"Decorator Crab (Skeleton)", size:"1–2 in", spotted:true,
  desc:"The leftover shell of a small crab that camouflages itself with attached algae, sponge, and debris using hooked bristles.",
  role:"In life, its habit of decorating itself moves small organisms like sponge and algae fragments around the reef, spreading them to new surfaces."},
];
